<?php

if(isset($_POST['submit'])){
	$email = $_POST['email'];


echo $to = $email;
$from = "victorabayomi@gmail.com";
$subject = "MindWash Coming Soon!";
$body = "Thank you for subscribing, You will be notified when our app is launched"; 

$fromName = 'MindWash Inc.';

//header for sender info
$headers = "From: $fromName"." <".$from.">";

//boundary 
$semi_rand = md5(time()); 
$mime_boundary = "==Multipart_Boundary_x{$semi_rand}x"; 

//headers for attachment 
$headers .= "\nMIME-Version: 1.0\n" . "Content-Type: multipart/mixed;\n" . " boundary=\"{$mime_boundary}\""; 

//multipart boundary 
$message = "--{$mime_boundary}\n" . "Content-Type: text/html; charset=\"UTF-8\"\n" .
"Content-Transfer-Encoding: 7bit\n\n" . $body . "\n\n"; 


$message .= "--{$mime_boundary}--";
$returnpath = "-f" . $from;

//send email
$mail = mail($to, $subject, $message, $headers, $returnpath); 

if($mail){
	echo "EMAIL SENT !";
}else{
	echo "ERROR SENDING EMAIL";
}


// $separator = md5(time());

// // carriage return type (we use a PHP end of line constant)
// $eol = PHP_EOL;

// // attachment name
// // $filename = "";

// //$pdfdoc is PDF generated by FPDF
// // $attachment = chunk_split(base64_encode(file_get_contents($filename))); 

// // main header
// $headers  = "From:".$from.$eol;
// $headers .= "MIME-Version: 1.0".$eol; 
// $headers .= "Content-Type: multipart/mixed; boundary=\"".$separator."\"";

// // no more headers after this, we start the body! //

// $body = "--".$separator.$eol;
// $body .= "Content-Transfer-Encoding: 7bit".$eol.$eol;
// $body .= $bdy.$eol;

// // message
// $body .= "--".$separator.$eol;
// $body .= "Content-Type: text/html; charset=\"iso-8859-1\"".$eol;
// $body .= "Content-Transfer-Encoding: 8bit".$eol.$eol;
// // $body .= $message.$eol;

// // attachment
// $body .= "--".$separator.$eol;
// // $body .= "Content-Type: application/octet-stream; name=\"".$filename."\"".$eol; 
// $body .= "Content-Transfer-Encoding: base64".$eol;
// $body .= "Content-Disposition: attachment".$eol.$eol;
// // $body .= $attachment.$eol;
// $body .= "--".$separator."--";

// // send message
// if (mail($to, $subject, $body, $headers)) {
//     echo "mail send ... OK";
// } else {
//     echo "mail send ... ERROR";
// }

// "-f crudanhq@crudan.org"

}else{
	echo "NO DATA RECEIVED";
}


?>